[core]
# Bật chế độ Kiosk, khóa thanh công cụ
shell=kiosk-shell.so
# Xóa con trỏ chuột (nếu dùng màn hình cảm ứng)
hide-cursor=true
#Tắt autosleep
idle-time = 0

[output]
# Thay đổi độ phân giải nếu cần
name=HDMI-A-1
mode=1920x1080
